name: integration

on:
  push:
    branches: [ main ]

jobs:
  publish:
    uses: aeternity/github-actions/.github/workflows/_publish-docker.yml@v2.2.0
    needs: [ validate ]
    secrets: inherit
    with:
      DOCKERHUB_REPO: "aeternity/${{ github.event.repository.name }}"
  deploy:
    uses: aeternity/github-actions/.github/workflows/_deploy-gitops.yml@v2.2.0
    needs: [publish]
    secrets: inherit
    with:
      DEPLOY_ENV: stg
      DEPLOY_APP: "${{ github.event.repository.name }}"
      DEPLOY_VERSION: main
      DEPLOY_SUBDOMAIN: "bridge"
